### ISSUE TITLE
Errors related to the 'thumbnail' property.

### ISSUE THREAD

**Issue by Jamie932** [node-xbmc/node-xbmc#10]
I've just tried using the 'Kodi Missing Episodes' script and have run into a problem which the author has attributed to node-xbmc. The error can be seen in timdp/kodi-missing-episodes#2 and the series that it is having problems with is 'Come Fly With Me' (#13).

**Comment by timdp** [comment]
I just ran a quick test by making kodi-missing-episodes search for Come Fly With Me. It's not throwing any errors for that show (or any others on my end).

Are you using the latest version of my script? Currently, it's about a month old, but it should come with the latest versions of all its dependencies, so it shouldn't be a versioning problem.

If you run `set DEBUG=*` and then start my script again, you should see a whole bunch of debugging information from node-xbmc fly by. Could you post that here?

By the way, the #13 shouldn't matter for node-xbmc. It's specific to your Kodi installation.

**Comment by timdp** [comment]
@Jamie932 Now that #14 has been merged in, can you check if the latest version of kodi-missing-episodes still errors out? Thanks.

**Comment by Jamie932** [comment]
Apologies for not following through with the debug - completely forgot about it. This update does fix the problem it seems and I can now run it through my entire collection properly! Well done in isolating this issue.

**Comment by timdp** [comment]
Awesome!
